#!/usr/bin/env sh

./gradlew --no-daemon --quiet spotlessApply
if [ $? -ne 0 ]; then
  echo "Spotless formatting failed. Please fix the issues and try again."
  exit 1
else
  echo "Spotless formatting applied successfully."
fi